### ISSUE TITLE
位图字体&图片填充&高级组点击

### ISSUE THREAD

**Issue by ifWater** [fairygui/FairyGUI-cocoscreator#15]
经测试官方Demo和自己制作的Demo以及实际项目使用中发现：
1.位图字体在组件套组件中会出现偏移（左右居中向上偏一点，上下居中向下偏一点），组件中正常
2.高级组点击无效（不知是Bug还是本来不可用）
3.图片填充采用：垂直-起点为下的方式，填充表现为旋转填充

1.设计图
![image](https://user-images.githubusercontent.com/42797776/57194743-f2b3ac80-6f7c-11e9-88a9-3e03c126afad.png)
2.运行图
![image](https://user-images.githubusercontent.com/42797776/57194754-1aa31000-6f7d-11e9-878c-02a983d5be9d.png)

引擎版本：2.0.7
测试用Demo：
[BugDemo.zip](https://github.com/fairygui/FairyGUI-cocoscreator/files/3145566/BugDemo.zip)

然后提个建议呗：
谷主有时间可以支持下字体描边么（cocoscreator据我看到的2.0.7版本可以用LabelOutline组件进行描边）

**Comment by xiaoguzhu** [comment]
高级组不是显示对象，自然是没有点击的。
描边不是一直都支持吗。
其他我查一查。

**Comment by ifWater** [comment]
嗯嗯，描边可以用，疏忽了。
还有一个问题是：当字体选择自动宽高模式时，字体上面会被切割，
设计图：
![image](https://user-images.githubusercontent.com/42797776/57206864-a196cd80-6ffb-11e9-96ed-ea8e2f646a6a.png)
运行图：
![image](https://user-images.githubusercontent.com/42797776/57206873-b5423400-6ffb-11e9-8d40-4371dc7035f1.png)

**Comment by ifWater** [comment]
图片填充问题我已经发现了
![image](https://user-images.githubusercontent.com/42797776/58167015-a2975280-7cbd-11e9-936c-ea60bfea4199.png)
因为ccc里面枚举是从0开始的，，所以这里应该减1
