### ISSUE TITLE
Cocos2.09遮罩问题

### ISSUE THREAD

**Issue by ifWater** [fairygui/FairyGUI-cocoscreator#18]
在使用中发现2.09的反向遮罩点击，会出现被遮挡的地方点击也有效的问题

以前用2.07没这个问题

通过观察CC源码发现是官方做了修改
![image](https://user-images.githubusercontent.com/42797776/58154916-4e807400-7ca5-11e9-97c8-673100bb4562.png)
![image](https://user-images.githubusercontent.com/42797776/58154929-5d672680-7ca5-11e9-879e-b1ff5cab7e27.png)

然后我修改了下fgui的源码，
![image](https://user-images.githubusercontent.com/42797776/58155102-d36b8d80-7ca5-11e9-8a9e-6c41b955295f.png)
反向遮罩暂时没问题，因为没有通读整个源码，但是担心这样改会出现其他问题，所以还是官方处理下吧

**Comment by xiaoguzhu** [comment]
我用2.1.0测试Demo 新手向导，这里用到了反向遮罩，没看到有问题。你自己测试一下。

**Comment by ifWater** [comment]
嗯，我重新测试了一下：

没问题的版本：2.0.7 & 2.1.0

有问题的版本：2.0.9 & 2.0.10 & 2.1.1

**Comment by xiaoguzhu** [comment]
那我只想吐槽一句，cocos官方在搞什么。
