### ISSUE TITLE
富文本导致设置的位图字体变为默认字体

### ISSUE THREAD

**Issue by ifWater** [fairygui/FairyGUI-cocoscreator#19]
![image](https://user-images.githubusercontent.com/42797776/59603522-3254e300-913c-11e9-9893-66e0b56a4606.png)
我打印这个value属性发现为
![image](https://user-images.githubusercontent.com/42797776/59603549-47ca0d00-913c-11e9-8da2-6062b795146f.png)

测试引擎版本2.09

**Comment by xiaoguzhu** [comment]
ccc的富文本设置字体只接受一个TTF对象，所以应该是不支持位图文本的。
