### ISSUE TITLE
按钮模拟触发点击异常

### ISSUE THREAD

**Issue by ifWater** [fairygui/FairyGUI-cocoscreator#20]
Button.fireClick();这个Api，，实际使用中发现，，可以触发注册的回调，，但是没有模拟点击的效果，，但是教程是
![image](https://user-images.githubusercontent.com/42797776/59605484-7ac2cf80-9141-11e9-96ad-84e3092e58b9.png)

**Comment by xiaoguzhu** [comment]
这个目前是连续调用了按下释放时间，没有时间差，所以是看不到效果的。以后有时间再修改吧，或者自行修改。
