### ISSUE TITLE
2.1.2版本，GLoader设置autoSize和锚点设为中心时，不兼容

### ISSUE THREAD

**Issue by HuangYuGH** [fairygui/FairyGUI-cocoscreator#24]
GLoader设置autoSize和锚点设为中心时，不兼容。
已解决，代码如下，
`
GLoader.prototype.updateLayout = function () {
....

if (this._autoSize) {
                this._updatingLayout = true;
                if (this._contentWidth == 0)
                    this._contentWidth = 50;
                if (this._contentHeight == 0)
                    this._contentHeight = 30;
                this.setSize(this._contentWidth, this._contentHeight);
                this._updatingLayout = false;
                this._container.setContentSize(this._width, this._height);
                //change by MixMarvel
                // this._container.setPosition(pivotCorrectX, pivotCorrectY);
                this._container.setPosition(-this.pivotX * this._width, this.pivotY * this._height);
                if (this._content2 != null) {
                    this._content2.setPosition(pivotCorrectX - this._width / 2, pivotCorrectY - this._height / 2);
                    this._content2.setScale(1, 1);
                }
                if (this._contentWidth == this._width && this._contentHeight == this._height)
                    return;
            }
......

`

**Comment by LookeLee** [comment]
还是不行，我把整个方法都替换到以前版本的代码，就可以了
GLoader.prototype.updateLayout = function () {
            if (this._content2 == null && this._content == null) {
                if (this._autoSize) {
                    this._updatingLayout = true;
                    this.setSize(50, 30);
                    this._updatingLayout = false;
                }
                return;
            }
            this._contentWidth = this._contentSourceWidth;
            this._contentHeight = this._contentSourceHeight;
            if (this._autoSize) {
                this._updatingLayout = true;
                if (this._contentWidth == 0)
                    this._contentWidth = 50;
                if (this._contentHeight == 0)
                    this._contentHeight = 30;
                this.setSize(this._contentWidth, this._contentHeight);
                this._updatingLayout = false;
                this._container.setContentSize(this._width, this._height);
                if (this._content2 != null)
                    this._content2.setPosition(-this._width / 2, -this._height / 2);
                if (this._contentWidth == this._width && this._contentHeight == this._height)
                    return;
            }
            var sx = 1, sy = 1;
            if (this._fill != fgui.LoaderFillType.None) {
                sx = this.width / this._contentSourceWidth;
                sy = this.height / this._contentSourceHeight;
                if (sx != 1 || sy != 1) {
                    if (this._fill == fgui.LoaderFillType.ScaleMatchHeight)
                        sx = sy;
                    else if (this._fill == fgui.LoaderFillType.ScaleMatchWidth)
                        sy = sx;
                    else if (this._fill == fgui.LoaderFillType.Scale) {
                        if (sx > sy)
                            sx = sy;
                        else
                            sy = sx;
                    }
                    else if (this._fill == fgui.LoaderFillType.ScaleNoBorder) {
                        if (sx > sy)
                            sy = sx;
                        else
                            sx = sy;
                    }
                    if (this._shrinkOnly) {
                        if (sx > 1)
                            sx = 1;
                        if (sy > 1)
                            sy = 1;
                    }
                    this._contentWidth = this._contentSourceWidth * sx;
                    this._contentHeight = this._contentSourceHeight * sy;
                }
            }
            this._container.setContentSize(this._contentWidth, this._contentHeight);
            if (this._content2 != null) {
                this._content2.setPosition(-this._width / 2, -this._height / 2);
                this._content2.setScale(sx, sy);
            }
            var nx, ny;
            if (this._align == fgui.AlignType.Center)
                nx = 0;
            else if (this._align == fgui.AlignType.Right)
                nx = Math.floor((this._width - this._contentWidth) / 2);
            else
                nx = -Math.floor((this._width - this._contentWidth) / 2);
            if (this._verticalAlign == fgui.VertAlignType.Middle)
                ny = 0;
            else if (this._verticalAlign == fgui.VertAlignType.Bottom)
                ny = -Math.floor((this._height - this._contentHeight) / 2);
            else
                ny = Math.floor((this._height - this._contentHeight) / 2);
            this._container.setPosition(nx, ny);
        };

**Comment by xiaoguzhu** [comment]
不明白不兼容是什么意思。你用最新代码再测试。
