### ISSUE TITLE
What needs to change for v2.2?

### ISSUE THREAD

**Issue by jgod** [fairygui/FairyGUI-cocoscreator#27]
I will get around to testing this, but there are some great new performance increases and features, and some breaking changes. Does it effect FairyGUI?

https://discuss.cocos2d-x.org/t/cocos-creator-v2-2-0-released/47937

- Best regards

**Comment by xiaoguzhu** [comment]
Yes. It has been tested under cocos creator v2.2.

**Comment by xiaoguzhu** [comment]
We have tested  it under cocos creator v2.2。

**Comment by davyzhang** [comment]
confirmed, it works on 2.2.0 ccc
