### ISSUE TITLE
GTextField使用位图字体时不能动态改变颜色, 编辑器里面可以修改

### ISSUE THREAD

**Issue by davyzhang** [fairygui/FairyGUI-cocoscreator#29]
```typescript
let lbl = word.getChild('lblWord') as fgui.GLabel;
lbl.asTextField.color = new cc.Color(255, 255, 255, 255);
```
字体在是在IDE里面导入的位bmfont已经设置了可以动态设置颜色
![image](https://user-images.githubusercontent.com/576863/69338025-302a1e00-0cb2-11ea-8a94-a4c65d4e5edb.png)

使用系统字体渲染,以上设置可以正常修改颜色

**Comment by xiaoguzhu** [comment]
demo测试正常。

题外话， as GLabel 然后又 asTextField，但这两个类型是毫不相关的。当然，js无类型，这个可能也不会出什么问题。

**Comment by davyzhang** [comment]
谢谢, 是我自己的问题, 我用最小的项目不能重现. 我看看到底是什么地方没写对
