### ISSUE TITLE
关于fgui.UIObjectFactory.setExtension功能的使用

### ISSUE THREAD

**Issue by wildfire810** [fairygui/FairyGUI-cocoscreator#30]
您好，是这样，我这边有员工在项目中使用了fgui.UIObjectFactory.setExtension功能
确实是挺方便的，但是我们没有在官方文档上找到。也许是我的疏忽。
想请问一下，这个文档在哪个章节，方便的话直接给URL更好；这个API如果还没有文档化，是否还处于不稳定阶段，设计上是否会移除或者做调整，如果我们用在项目中，是否有风险？
谢谢

**Comment by xiaoguzhu** [comment]
教程 组件。基础功能，没有风险。

**Comment by wildfire810** [comment]
谢谢你的回答

FairyGUI - 组件
http://www.fairygui.com/guide/editor/component.html

我没有检索到setExtension这个函数，倒是找到了SetPackageItemExtension
应该只是不同语言里面同一个功能函数的不同声明吧。：）
