### ISSUE TITLE
升级2.4碰到了一个问题

### ISSUE THREAD

**Issue by cocospupil** [fairygui/FairyGUI-cocoscreator#44]
protected onConstruct() {

        this._backGround = this.getChild("backGround");
        this._guideLayer = this.getChild("guideLayer");
        this._guideLayer.setPivot(0.5, 0.5, true);
    }

    public GuidePlayer(target: fgui.GComponent) {
        let screenPos = target.localToGlobal(0, 0);
        let localPos = this.globalToLocal(screenPos.x, screenPos.y);
        this._guideLayer.setSize(target.width, target.height);
        fgui.GTween.to2(this._guideLayer.x, this._guideLayer.y, localPos.x, localPos.y, 0.5).setTarget(this._guideLayer, this._guideLayer.setPosition);
    }

同样的代码在之前2.3.4版本可以到达正确的位置 target的锚点也是setPivot(0.5,0.5,true) 升级到2.4 发现到达的位置是左上角..

**Comment by xiaoguzhu** [comment]
target.localToGlobal(0,0)，这不是target的左上角位置吗

**Comment by cocospupil** [comment]
这个问题我也有考虑过&nbsp; 因为之前对这个参数的了解也不是很深 也尝试改过这个地方到0.5 0.5 不过效果是一样的 主要是没升级之前 这里写的0 0 也没问题///




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "guzhu"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 上午10:19
收件人: "fairygui/FairyGUI-cocoscreator"<FairyGUI-cocoscreator@noreply.github.com&gt;; 
抄送: "Eleven-11"<434920074@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fairygui/FairyGUI-cocoscreator] 升级2.4碰到了一个问题 (#44)





 
target.localToGlobal(0,0)，这不是target的左上角位置吗

**Comment by xiaoguzhu** [comment]
是的，这里可能有和以前不一致的问题，我改一下。

**Comment by cocospupil** [comment]
辛苦了 谷主




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "guzhu"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 上午10:37
收件人: "fairygui/FairyGUI-cocoscreator"<FairyGUI-cocoscreator@noreply.github.com&gt;; 
抄送: "Eleven-11"<434920074@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fairygui/FairyGUI-cocoscreator] 升级2.4碰到了一个问题 (#44)





 
是的，这里可能有和以前不一致的问题，我改一下。
