### ISSUE TITLE
什么时候支持creator 3.0 呢

### ISSUE THREAD

**Issue by bournes** [fairygui/FairyGUI-cocoscreator#49]
什么时候支持creator 3.0 呢

**Comment by x97888** [comment]
什么时候支持creator 3.0 呢

**Comment by yicong1406410220** [comment]
什么时候支持creator 3.0 呢

**Comment by imlihao** [comment]
什么时候支持creator 3.0 呢

**Comment by xiaoguzhu** [comment]
https://github.com/fairygui/FairyGUI-cocoscreator/tree/ccc3.0
