### ISSUE TITLE
Text使用UBB语法和加粗

### ISSUE THREAD

**Issue by ifWater** [fairygui/FairyGUI-cocoscreator#5]
在最新的Demo中，CocosCreator版本为2.0.7，使用Text组件，可发现两个问题，
1.编辑器中对其加粗，，实际运行中无效果
2.编辑器中使用UBB语法对其加粗，实际运行无效果
![image](https://user-images.githubusercontent.com/42797776/51474644-ef742680-1dba-11e9-81a6-c24751ea5bf4.png)
![image](https://user-images.githubusercontent.com/42797776/51474681-06b31400-1dbb-11e9-9597-9d88433e6931.png)

2.
![image](https://user-images.githubusercontent.com/42797776/51474765-3d892a00-1dbb-11e9-9036-a5b88abefe86.png)

![image](https://user-images.githubusercontent.com/42797776/51474755-3530ef00-1dbb-11e9-91d3-b613003cacf5.png)

**Comment by xiaoguzhu** [comment]
ccc的Text并不支持粗体，你敢信吗。。。用富文本吧。
