### ISSUE TITLE
富文本使用自动收缩和单行存在的问题

### ISSUE THREAD

**Issue by ifWater** [fairygui/FairyGUI-cocoscreator#6]
在最新的Demo中，CocosCreator版本为2.0.7
富文本使用自动收缩，预览正常，实际运行无效果
![image](https://user-images.githubusercontent.com/42797776/51474940-e0da3f00-1dbb-11e9-9f3c-00b07d8aa7b0.png)
![image](https://user-images.githubusercontent.com/42797776/51474980-02d3c180-1dbc-11e9-8088-c63ea1896426.png)

可以发现，当我更改了Demo中的文本框大小，且勾选自动收缩，在编辑器中正常，实际运行中发现文本框大小已改变，但是字体大小却没有收缩

2.富文本使用单行（这个问题不知是我使用错误，还是Bug,看一下呗）
![image](https://user-images.githubusercontent.com/42797776/51475133-7fff3680-1dbc-11e9-9c3f-21212f99d67f.png)
![image](https://user-images.githubusercontent.com/42797776/51475198-a1f8b900-1dbc-11e9-84b9-4a44cb452cef.png)

我通过将编辑器中富文本框的大小改为固定长度，并选中单行模式，在实际运行中可发现文本框长度正常，但是文本却换行了，而不是我理想中的单行

**Comment by xiaoguzhu** [comment]
富文本实际使用的是ccc的RichText控件，具体特性和行为由后者决定，FairyGUI的特性它不一定都能支持。
