### ISSUE TITLE
Cocos Creator 3.4报错

### ISSUE THREAD

**Issue by 15335179243** [fairygui/FairyGUI-cocoscreator#70]
![image](https://user-images.githubusercontent.com/50068045/147754175-42532743-7ea8-468a-9230-f0f036047ced.png)

**Comment by xiaoguzhu** [comment]
已经有小伙伴PR改好了

**Comment by 15335179243** [comment]
麻烦把提交标注一下

**Comment by 15335179243** [comment]
> 已经有小伙伴PR改好了

能不能发一下npm
