### ISSUE TITLE
Cocos Crator3.6出现错误

### ISSUE THREAD

**Issue by huahuacn** [fairygui/FairyGUI-cocoscreator#78]
![image](https://user-images.githubusercontent.com/31203217/192137072-bc172b3e-79e3-4d9f-b8d1-0f6d3df80e4e.png)

如图，希望能更新一下。

**Comment by huahuacn** [comment]
是我弄错了~

**Comment by endison1986** [comment]
一样的报错，怎么处理的？

**Comment by huahuacn** [comment]
> 一样的报错，怎么处理的？

自己改掉build一份，我自己build发现覆盖错了，所以关掉了
