### ISSUE TITLE
List边缘留空 留空的地方没办法拖动

### ISSUE THREAD

**Issue by lamatimo** [fairygui/FairyGUI-cocoscreator#81]
![image](https://user-images.githubusercontent.com/42297620/215761911-f8a6ba4c-aa7d-44a8-bb98-efc7294be95e.png)
![1de8db7a5935031539bc2becfbc6a9b](https://user-images.githubusercontent.com/42297620/215763365-34cdb295-dcfe-4a58-8c48-08af1ceae749.png)

如图 顶部留了200距离 但是没办法触摸滑动 我看unity是可以的

**Comment by xiaoguzhu** [comment]
fix in https://github.com/fairygui/FairyGUI-cocoscreator/commit/ee018f6a65043a953b9fce76dfb4d81aa2097e5b
