### ISSUE TITLE
List的mouseWheel依旧还有Bug

### ISSUE THREAD

**Issue by PandKent** [fairygui/FairyGUI-cocoscreator#9]
如果list不是虚拟列表，那么mouseWheel使用没有任何问题
但如果list设置成虚拟列表后，那么mouseWheel的滚动并不符合预期

**Comment by xiaoguzhu** [comment]
不懂什么意思。

**Comment by PandKent** [comment]
谷主 你可以试一试，把一个列表设成虚拟列表后，试试用鼠标滚轴滚动，滚动效果非常不顺畅，但是如果列表不是虚拟列表的话，滚动的非常顺畅

**Comment by xiaoguzhu** [comment]
测试Demo没有发现问题。

**Comment by xiaoguzhu** [comment]
没收到进一步反馈，假设问题已解决。
